Update test
42ity/fty-nut pull request #257
Opened 2021-05-07 10:51 UTC by eric3873

Update test to pass with Jenkins
**IMPORTANT NOTE: Need to merge nut PR #132 Add mock for TcpClient.**

2021-05-17 07:32 UTC, perrettecl approved these changes

2021-05-17 08:52 UTC, perrettecl requested changes

2021-05-17 08:52 UTC, perrettecl commented on lib/CMakeLists.txt
> +        nutclientstub
Is it needed for the lib or only for test? If it's only for tests, it should not be part of the lib and not be part of the package too. If it's needed also for the runtime package, you need to upgrade the simple image to add the package inside.

2021-07-19 09:17 UTC, jeffdegott approved these changes

2021-07-19 09:17 UTC, jeffdegott commented on lib/src/sensor_list.cc
> +#include <nutclientmem.h>
naming convention and readability?

2021-07-19 09:17 UTC, jeffdegott commented on lib/src/sensor_list.h
> +    void removeInventory(std::string name);
prefer const std::string&

2021-07-19 09:17 UTC, jeffdegott commented on lib/tests/sensors.cpp
> +    fty_proto_set_name (asset, "ups-1");
REQUIRE(asset)  ?

2021-07-19 09:17 UTC, jeffdegott commented on packaging/debian/control
> +Source:         fty-nut
tabs are usefull here?

2021-08-02 11:39 UTC, aquette approved these changes

2021-08-02 11:39 UTC, merged